modLoader="javafml"
loaderVersion="[32,)"
license="All rights reserved"

[[mods]]
modId="canopy" #mandatory
version="${file.jarVersion}"
displayName="Canopy"
logoFile="canopy.png"
credits="Thanks to Team Abnormals for creating Neapolitan."
authors="Epic312, Evo, DavidStain"
description='''Neapolitan addon that adds blueberries.'''

[[dependencies.canopy]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.canopy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.canopy]]
    modId="neapolitan"
    mandatory=true
    versionRange="[2.0.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.canopy]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[3.0.6,)"
    ordering="AFTER"
    side="BOTH"